### ISSUE TITLE
Issues building the release package

### ISSUE THREAD

**Issue by Winter870** [holly-hacker/ce-server#3]
![image](https://github.com/user-attachments/assets/74fb1718-2363-4eb3-8c73-bd8bba2a6a5e)
Got an error message while building the package, used the command "cargo build --release" in the ce-server-master directory. The "cargo run" command after this produced these results:
![image](https://github.com/user-attachments/assets/ecc3a027-5619-4a6b-9cee-306a8f94d52b)

**Comment by holly-hacker** [comment]
For now, consider following the instructions in the error message by runnning `cargo update`. I'll see if I can get to updating this later.

**Comment by holly-hacker** [comment]
Fixed in 2ef0876612a5529da03c5a528ca303bf3778f535.

I don't have a Windows machine to test right now so I can't test if anything else works, but now it does build.
